### ISSUE TITLE
Doubt

### ISSUE THREAD

**Issue by cjdduarte** [ijgnd/anki__misc#1]
This addon you are creating will allow new cards to be displayed randomly. It is?

**Comment by cjdduarte** [comment]
Hi?

**Comment by ijgnd** [comment]
sorry for answering so late. I didn't get a notification. I changed some settings. Hopefully I'll get notified about all new issues. To test this: Could you open a new blank issue in any of my repos?

----

this add-on should make changing the relevant Preferences entry a little bit quicker. It affects this setting:, https://apps.ankiweb.net/docs/manual.html#preferences  "The second drop-down box controls when new cards are shown: either mixed with, before, or after all reviews."

I just added this description: 

# allows to quickly change when new cards are shown.
# Usually you have to go to the Preferences to adjust this
# This add-on offers shortcuts and entries in the "More" 
# menu (lower right corner)

My motivation: Usually I like to mix new cards and reviews. Sometimes before I finish all reviews I add a bunch of new cards with information that's hard to memorize . I need to quickly view these for the first time so that I don't forget them. For these I need "show new cards first". After I have viewed them I want to be able to quickly switch back to "mixing".

**Comment by ijgnd** [comment]
I just updated the styling of previous comment ...

**Comment by cjdduarte** [comment]
interesting. Sometimes I do this often. I'll wait for the publication.

I created the topic. See if you received the notification.
